/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Represents a webview application */
export declare class Application {
  /** Creates a new application */
  constructor(options?: ApplicationOptions | undefined | null)
  /** Sets the event callback */
  onEvent(handler?: ((arg: ApplicationEvent) => void) | undefined | null): void
  /** Alias for on_event() - binds an event callback */
  bind(handler?: ((arg: ApplicationEvent) => void) | undefined | null): void
  /** Creates a new browser window */
  createBrowserWindow(options?: BrowserWindowOptions | undefined | null): BrowserWindow
  /** Creates a new browser window as a child window */
  createChildBrowserWindow(options?: BrowserWindowOptions | undefined | null): BrowserWindow
  /** Exits the application gracefully */
  exit(): void
  /**
   * Runs the application in blocking mode
   *
   * This method will block the current thread until the application terminates.
   * Note: This will block the Node.js event loop.
   */
  run(): void
  /**
   * Runs the application with a worker thread (future)
   *
   * This method will allow the UI event loop to run on the main thread
   * while a worker thread handles business logic without blocking Node.js.
   *
   * TODO: Implement this functionality
   */
  runWithWorker(workerCallback: ((err: Error | null, arg: string) => any)): void
  /**
   * Runs the application in detached mode (future)
   *
   * This method will allow the server to keep running after
   * the window is closed.
   *
   * TODO: Implement this functionality
   */
  runDetached(keepServerAlive: boolean): void
}

export declare class BrowserWindow {
  /** Creates a webview on this window. */
  createWebview(options?: WebviewOptions | undefined | null): JsWebview
  /** Whether or not the window is a child window. */
  get isChild(): boolean
  /** Whether the window is focused. */
  isFocused(): boolean
  /** Whether the window is visible. */
  isVisible(): boolean
  /** Whether the window is decorated. */
  isDecorated(): boolean
  /** Whether the window is closable. */
  isClosable(): boolean
  /** Whether the window is maximizable. */
  isMaximizable(): boolean
  /** Whether the window is minimizable. */
  isMinimizable(): boolean
  /** Whether the window is maximized. */
  isMaximized(): boolean
  /** Whether the window is minimized. */
  isMinimized(): boolean
  /** Whether the window is resizable. */
  isResizable(): boolean
  /** Sets the window title. */
  setTitle(title: string): void
  /** Sets the window title. */
  get title(): string
  /** Sets closable. */
  setClosable(closable: boolean): void
  /** Sets maximizable. */
  setMaximizable(maximizable: boolean): void
  /** Sets minimizable. */
  setMinimizable(minimizable: boolean): void
  /** Sets resizable. */
  setResizable(resizable: boolean): void
  /** Gets the window theme. */
  get theme(): Theme
  /** Sets the window theme. */
  setTheme(theme: Theme): void
  /** Sets the window icon. */
  setWindowIcon(icon: Array<number> | string, width: number, height: number): void
  /** Removes the window icon. */
  removeWindowIcon(): void
  /**
   * Modifies the window's visibility.
   * If `false`, this will hide all the window. If `true`, this will show the window.
   */
  setVisible(visible: boolean): void
  /** Modifies the window's progress bar. */
  setProgressBar(state: JsProgressBar): void
  /** Maximizes the window. */
  setMaximized(value: boolean): void
  /** Minimizes the window. */
  setMinimized(value: boolean): void
  /** Bring the window to front and focus. */
  focus(): void
  /** Get available monitors. */
  getAvailableMonitors(): Array<Monitor>
  /** Get the current monitor. */
  getCurrentMonitor(): Monitor | null
  /** Get the primary monitor. */
  getPrimaryMonitor(): Monitor | null
  /** Get the monitor from the given point. */
  getMonitorFromPoint(x: number, y: number): Monitor | null
  /** Prevents the window contents from being captured by other apps. */
  setContentProtection(enabled: boolean): void
  /** Sets the window always on top. */
  setAlwaysOnTop(enabled: boolean): void
  /** Sets always on bottom. */
  setAlwaysOnBottom(enabled: boolean): void
  /** Turn window decorations on or off. */
  setDecorations(enabled: boolean): void
  /** Gets the window's current fullscreen state. */
  get fullscreen(): FullscreenType | null
  /** Sets the window to fullscreen or back. */
  setFullscreen(fullscreenType?: FullscreenType | undefined | null): void
  /**
   * Closes the window by hiding it. Note: This hides the window rather than closing it completely,
   * as tao requires the event loop to handle window closing. Use this when you want to
   * close a specific window (like a login window) and potentially reopen it later.
   */
  close(): void
  /** Hides the window without destroying it. */
  hide(): void
  /** Shows the window if it was hidden. */
  show(): void
}

export declare class Webview {
  constructor()
  /** Sets the IPC handler callback. */
  onIpcMessage(handler?: ((arg: IpcMessage) => void) | undefined | null): void
  /** Launch a print modal for this window's contents. */
  print(): void
  /** Set webview zoom level. */
  zoom(scaleFactor: number): void
  /** Hides or shows the webview. */
  setWebviewVisibility(visible: boolean): void
  /** Whether the devtools is opened. */
  isDevtoolsOpen(): boolean
  /** Opens the devtools. */
  openDevtools(): void
  /** Closes the devtools. */
  closeDevtools(): void
  /** Loads the given URL. */
  loadUrl(url: string): void
  /** Loads the given HTML content. */
  loadHtml(html: string): void
  /** Evaluates the given JavaScript code. */
  evaluateScript(js: string): void
  evaluateScriptWithCallback(js: string, callback: ((err: Error | null, arg: string) => any)): void
  /** Reloads the webview. */
  reload(): void
}
export type JsWebview = Webview

/** Event for the application */
export interface ApplicationEvent {
  /** The event type */
  event: WebviewApplicationEvent
}

/** Options for creating an application */
export interface ApplicationOptions {
  /** The control flow of the application. Default is `Poll` */
  controlFlow?: ControlFlow
  /** The waiting time in ms for the application (only applicable if control_flow is set to `WaitUntil`) */
  waitTime?: number
  /** The exit code of the application. Only applicable if control_flow is set to `ExitWithCode` */
  exitCode?: number
}

/** Options for creating a browser window */
export interface BrowserWindowOptions {
  /** Whether window is resizable. Default is `true`. */
  resizable?: boolean
  /** The window title. */
  title?: string
  /** The width of window. */
  width?: number
  /** The height of window. */
  height?: number
  /** The x position of window. */
  x?: number
  /** The y position of window. */
  y?: number
  /** Whether or not window should be created with content protection mode. */
  contentProtection?: boolean
  /** Whether or not window is always on top. */
  alwaysOnTop?: boolean
  /** Whether or not window is always on bottom. */
  alwaysOnBottom?: boolean
  /** Whether or not window is visible. */
  visible?: boolean
  /** Whether or not window decorations are enabled. */
  decorations?: boolean
  /** Whether or not window is visible on all workspaces. */
  visibleOnAllWorkspaces?: boolean
  /** Whether or not window is maximized. */
  maximized?: boolean
  /** Whether or not window is maximizable. */
  maximizable?: boolean
  /** Whether or not window is minimizable. */
  minimizable?: boolean
  /** Whether or not window is focused. */
  focused?: boolean
  /** Whether or not window is transparent. */
  transparent?: boolean
  /** The fullscreen state of window. */
  fullscreen?: FullscreenType
}

/** Application control flow (mapped from tao::ControlFlow) */
export declare const enum ControlFlow {
  /** The application will continue running */
  Poll = 0,
  /** The application will wait until the specified time */
  WaitUntil = 1,
  /** The application will exit */
  Exit = 2,
  /** The application will exit with the given exit code */
  ExitWithCode = 3
}

/** Dimensions */
export interface Dimensions {
  /** The width of the size */
  width: number
  /** The height of the size */
  height: number
}

/** Fullscreen type */
export declare const enum FullscreenType {
  /** Exclusive fullscreen */
  Exclusive = 0,
  /** Borderless fullscreen */
  Borderless = 1
}

/** Returns the webview version */
export declare function getWebviewVersion(): string

/** HTTP header data */
export interface HeaderData {
  /** The header key */
  key: string
  /** The header value */
  value?: string
}

/** IPC message */
export interface IpcMessage {
  /** The message body */
  body: Buffer
  /** The HTTP method of the message */
  method: string
  /** The HTTP headers of the message */
  headers: Array<HeaderData>
  /** The URI of the message */
  uri: string
}

/** Progress bar */
export interface JsProgressBar {
  /** The progress state */
  state?: ProgressBarState
  /** The progress value */
  progress?: number
}

/** Monitor */
export interface Monitor {
  /** The name of the monitor */
  name?: string
  /** The scale factor of the monitor */
  scaleFactor: number
  /** The size of the monitor */
  size: Dimensions
  /** The position of the monitor */
  position: Position
  /** The video modes of the monitor */
  videoModes: Array<VideoMode>
}

/** Position */
export interface Position {
  /** The x position */
  x: number
  /** The y position */
  y: number
}

/** Progress bar state */
export declare const enum ProgressBarState {
  None = 0,
  Normal = 1,
  /** Treated as normal in Linux and macOS */
  Indeterminate = 2,
  /** Treated as normal in Linux */
  Paused = 3,
  /** Treated as normal in Linux */
  Error = 4
}

/** Window theme */
export declare const enum Theme {
  /** Light theme */
  Light = 0,
  /** Dark theme */
  Dark = 1,
  /** System theme */
  System = 2
}

/** Video mode */
export interface VideoMode {
  /** The size of the video mode */
  size: Dimensions
  /** The bit depth of the video mode */
  bitDepth: number
  /** The refresh rate of the video mode */
  refreshRate: number
}

/** Webview application events */
export declare const enum WebviewApplicationEvent {
  /** Window close event */
  WindowCloseRequested = 0,
  /** Application close event */
  ApplicationCloseRequested = 1
}

/** Options for creating a webview */
export interface WebviewOptions {
  /** The URL to load. */
  url?: string
  /** The HTML content to load. */
  html?: string
  /** The width of window. */
  width?: number
  /** The height of window. */
  height?: number
  /** The x position of window. */
  x?: number
  /** The y position of window. */
  y?: number
  /** Whether to enable devtools. Default is `true`. */
  enableDevtools?: boolean
  /** Whether window is incognito. Default is `false`. */
  incognito?: boolean
  /** The default user agent. */
  userAgent?: string
  /** Whether webview should be built as a child. */
  child?: boolean
  /** The preload script to inject. */
  preload?: string
  /** Whether window is transparent. Default is `false`. */
  transparent?: boolean
  /** The default theme. */
  theme?: Theme
  /** Whether window is zoomable via hotkeys or gestures. */
  hotkeysZoom?: boolean
  /** Whether clipboard access is enabled. */
  clipboard?: boolean
  /** Whether autoplay policy is enabled. */
  autoplay?: boolean
  /** Indicates whether horizontal swipe gestures trigger backward and forward page navigation. */
  backForwardNavigationGestures?: boolean
}

/** Window commands that can be sent from JavaScript */
export declare const enum WindowCommand {
  /** Close the window */
  Close = 0,
  /** Show the window */
  Show = 1,
  /** Hide the window */
  Hide = 2
}
